#! /usr/bin/env python
import sys
from collections import OrderedDict

def revcom(s):
	"""Return reverse complement of a sequence"""
	def complement(s):
			basecomplement = {'A': 'T', 'C': 'G', 'G': 'C', 'T': 'A', 'N': 'N'}
			letters = list(s)
			letters = [basecomplement[base] for base in letters]
			return ''.join(letters)
	return complement(s[::-1])


class fasta:
	"""
	Class to represent fasta seuqnces in a python dict.

	Args:
		filename(str): Location of the fasta file

	Returns:
		fasta: A fasta class object
	"""
	def __init__(self,FH):
		fa_dict = OrderedDict()
		seq_name = ""
		for l in FH:
			line = l.rstrip()
			if line.startswith(">"):
				seq_name = line[1:].split()[0]
				fa_dict[seq_name] = []
			else:
				fa_dict[seq_name].append(line)
		result = {}
		counter = 0
		sum_length = {}
		for seq in fa_dict:
			result[seq] = "".join(fa_dict[seq])
			result[seq] = result[seq].upper()
			sum_length[(counter+1,counter+len(result[seq]))] = seq
			counter = counter+len(result[seq])
		self.sum_length = sum_length
		self.fa_dict = result
	def revcom(self):
		for s in self.fa_dict:
			print(">%s\n%s" % (s,revcom(self.fa_dict[s])))


fa = fasta(sys.stdin)
fa.revcom()
